version: "3.9"

services:

  wildfly:
    image: bitnami/wildfly:latest

    ports:
      - "19990:9990"
      - "18080:8080"

    environment:
      WILDFLY_USERNAME: manager
      WILDFLY_PASSWORD: Adm14admin!
      WILDFLY_MANAGEMENT_LISTEN_ADDRESS: 0.0.0.0
